/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GuessMyNumber;

import java.awt.*;
import javax.swing.*;

/**
 * @author Admin
 */
public class GMN extends javax.swing.JFrame {

    /**
     * Creates new form GMN
     */
    public GMN() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    bg = new javax.swing.JPanel();
    title = new javax.swing.JLabel();
    guessField = new javax.swing.JTextField();
    checkNumberBtn = new javax.swing.JButton();
    jLabel3 = new javax.swing.JLabel();
    hintLabel = new javax.swing.JLabel();
    jLabel5 = new javax.swing.JLabel();
    jLabel6 = new javax.swing.JLabel();
    againBtn = new javax.swing.JButton();
    scoreLabel = new javax.swing.JLabel();
    highScoreLabel = new javax.swing.JLabel();
    jPanel1 = new javax.swing.JPanel();
    guessLabel = new javax.swing.JLabel();
    jPanel2 = new javax.swing.JPanel();
    jPanel3 = new javax.swing.JPanel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle("Guess my number");
    setBackground(new java.awt.Color(51, 102, 255));
    setFont(new java.awt.Font("CaskaydiaCove Nerd Font Mono", 0, 14)); // NOI18N
    setLocationByPlatform(true);

    bg.setBackground(new java.awt.Color(204, 204, 204));
    bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    title.setFont(new java.awt.Font("CaskaydiaCove Nerd Font Mono", 0, 36)); // NOI18N
    title.setForeground(new java.awt.Color(255, 255, 255));
    title.setText("Guess My Number");
    bg.add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(259, 6, -1, -1));

    guessField.setFont(new java.awt.Font("CaskaydiaCove Nerd Font Mono", 0, 36)); // NOI18N
    guessField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
    guessField.setMaximumSize(new java.awt.Dimension(46, 53));
    guessField.setMinimumSize(new java.awt.Dimension(46, 53));
    guessField.setPreferredSize(new java.awt.Dimension(46, 53));
    bg.add(guessField, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, 88, -1));

    checkNumberBtn.setBackground(new java.awt.Color(153, 153, 153));
    checkNumberBtn.setFont(new java.awt.Font("CaskaydiaCove Nerd Font Mono", 0, 18)); // NOI18N
    checkNumberBtn.setForeground(new java.awt.Color(0, 0, 0));
    checkNumberBtn.setText("Check!");
    checkNumberBtn.setBorder(null);
    checkNumberBtn.setBorderPainted(false);
    checkNumberBtn.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        checkNumberBtnActionPerformed(evt);
      }
    });
    bg.add(checkNumberBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 400, 91, 38));

    jLabel3.setFont(new java.awt.Font("CaskaydiaCove Nerd Font Mono", 0, 14)); // NOI18N
    jLabel3.setForeground(new java.awt.Color(255, 255, 255));
    jLabel3.setText("(Between 1 and 20)");
    bg.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(692, 6, -1, -1));

    hintLabel.setFont(new java.awt.Font("CaskaydiaCove Nerd Font Mono", 0, 14)); // NOI18N
    hintLabel.setForeground(new java.awt.Color(255, 255, 255));
    hintLabel.setText("Start guessing...");
    bg.add(hintLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 329, -1, -1));

    jLabel5.setFont(new java.awt.Font("CaskaydiaCove Nerd Font Mono", 0, 14)); // NOI18N
    jLabel5.setForeground(new java.awt.Color(255, 255, 255));
    jLabel5.setText("Highscore:");
    jLabel5.setToolTipText("");
    bg.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 413, -1, -1));

    jLabel6.setFont(new java.awt.Font("CaskaydiaCove Nerd Font Mono", 0, 14)); // NOI18N
    jLabel6.setForeground(new java.awt.Color(255, 255, 255));
    jLabel6.setText("Score:");
    jLabel6.setToolTipText("");
    bg.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(612, 393, -1, -1));

    againBtn.setBackground(new java.awt.Color(153, 153, 153));
    againBtn.setFont(new java.awt.Font("CaskaydiaCove Nerd Font Mono", 0, 18)); // NOI18N
    againBtn.setForeground(new java.awt.Color(0, 0, 0));
    againBtn.setText("Again!");
    againBtn.setBorder(null);
    againBtn.setBorderPainted(false);
    againBtn.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        againBtnActionPerformed(evt);
      }
    });
    bg.add(againBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 13, 84, 43));

    scoreLabel.setFont(new java.awt.Font("CaskaydiaCove Nerd Font Mono", 0, 14)); // NOI18N
    scoreLabel.setForeground(new java.awt.Color(255, 255, 255));
    scoreLabel.setText("  ");
    scoreLabel.setToolTipText("");
    bg.add(scoreLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(672, 393, -1, -1));

    highScoreLabel.setFont(new java.awt.Font("CaskaydiaCove Nerd Font Mono", 0, 14)); // NOI18N
    highScoreLabel.setForeground(new java.awt.Color(255, 255, 255));
    highScoreLabel.setText("  ");
    highScoreLabel.setToolTipText("");
    bg.add(highScoreLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(672, 413, -1, -1));

    jPanel1.setBackground(new java.awt.Color(255, 255, 255));

    guessLabel.setBackground(new java.awt.Color(255, 255, 255));
    guessLabel.setFont(new java.awt.Font("CaskaydiaCove Nerd Font Mono", 0, 72)); // NOI18N
    guessLabel.setForeground(new java.awt.Color(0, 0, 0));
    guessLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    guessLabel.setText("?");

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 103, Short.MAX_VALUE)
      .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
          .addGap(30, 30, 30)
          .addComponent(guessLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addGap(31, 31, 31)))
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 100, Short.MAX_VALUE)
      .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
          .addContainerGap()
          .addComponent(guessLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addContainerGap()))
    );

    bg.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(381, 152, -1, -1));

    jPanel2.setBackground(new java.awt.Color(255, 255, 255));

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 390, Short.MAX_VALUE)
    );
    jPanel2Layout.setVerticalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 30, Short.MAX_VALUE)
    );

    bg.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 390, 30));

    jPanel3.setBackground(new java.awt.Color(255, 255, 255));

    javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
    jPanel3.setLayout(jPanel3Layout);
    jPanel3Layout.setHorizontalGroup(
      jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 360, Short.MAX_VALUE)
    );
    jPanel3Layout.setVerticalGroup(
      jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 31, Short.MAX_VALUE)
    );

    bg.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 190, 360, -1));

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(0, 0, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

    private int randomNumber;
    private int score;
    private int highScore;
    private boolean guessued;

    private final Color MY_GRAY = new Color(50, 50, 50);
    private final Color MY_GREEN = new Color(0, 163, 108);
    private final Color MY_RED = new Color(224, 17, 95);
    private final Color MY_ORANGE = new Color(255, 36, 0);


    private boolean isGuessued() {
        return this.guessued;
    }

    private void setGuessued(boolean guessued) {
        this.guessued = guessued;
    }

    private int getScore() {
        return this.score;
    }

    private void setScore(int score) {
        this.score = score;
    }

    private int getHighScore() {
        return this.highScore;
    }

    private void setHighScore(int highScore) {
        this.highScore = highScore;
    }

    private int getRandomNumber() {
        return this.randomNumber;
    }

    private void setRandomNumber(int randomNumber) {
        this.randomNumber = randomNumber;
    }

    private void againBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_againBtnActionPerformed
        if (this.getHighScore() > 0) {
            highScoreLabel.setText(Integer.toString(this.getHighScore()));
        }

        this.setScore(20);
        bg.setBackground(this.MY_GRAY);
        checkNumberBtn.setEnabled(true);
        guessField.setEnabled(true);
        guessField.setText("");
        hintLabel.setText("Start guessing...");
        guessLabel.setText("?");
        this.setRandomNumber((int) (Math.random() * 20) + 1);
        scoreLabel.setText(Integer.toString(this.getScore()));
        guessField.grabFocus();

    //GEN-LAST:event_againBtnActionPerformed
    }

    private void checkNumberBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkNumberBtnActionPerformed
        if (guessField.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Enter a number", "Error", JOptionPane.ERROR_MESSAGE);
            guessField.grabFocus();
            return;
        }
        int number = Integer.parseInt(guessField.getText());
        String text = "";
        if (this.getRandomNumber() == number) {
            bg.setBackground(this.MY_GREEN);
            hintLabel.setText("Great! Correct number");
            guessLabel.setText(Integer.toString(this.getRandomNumber()));
            if (this.getScore() > this.getHighScore()) {
                this.setHighScore(this.getScore());
            }
            guessField.setEnabled(false);
            checkNumberBtn.setEnabled(false);
            return;
        }

        if (number < this.getRandomNumber()) {
            hintLabel.setText("Too low!");
            text = "too low!";
        } else {
            hintLabel.setText("Too high!");
            text = "too high!";
        }
        this.setScore(this.getScore() - 1);

        scoreLabel.setText(Integer.toString(this.getScore()));
        if (this.getScore() == 0) {
            bg.setBackground(this.MY_RED);
            guessLabel.setText(Integer.toString(this.getRandomNumber()));
            hintLabel.setText("Game over!");
            checkNumberBtn.setEnabled(false);
            guessField.setEnabled(false);
        } else if(this.getScore() < 4){
            bg.setBackground(this.MY_ORANGE);
            hintLabel.setText("Hurry up! The number is " + text);
        }
        guessField.setText("");
        guessField.grabFocus();
    }//GEN-LAST:event_checkNumberBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        GMN gmn = new GMN();
        gmn.setRandomNumber((int) (Math.random() * 20) + 1);
        gmn.setScore(20);
        gmn.setHighScore(0);
        gmn.scoreLabel.setText("20");
        gmn.highScoreLabel.setText("0");
        gmn.guessField.setDocument(new GuessFilter());
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                gmn.bg.setBackground(gmn.MY_GRAY);
                gmn.setVisible(true);
            }
        });
    }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton againBtn;
  private javax.swing.JPanel bg;
  private javax.swing.JButton checkNumberBtn;
  private javax.swing.JTextField guessField;
  private javax.swing.JLabel guessLabel;
  private javax.swing.JLabel highScoreLabel;
  private javax.swing.JLabel hintLabel;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JPanel jPanel3;
  private javax.swing.JLabel scoreLabel;
  private javax.swing.JLabel title;
  // End of variables declaration//GEN-END:variables
}
